train:
  path: /../data/raw/shuffled_ccnews_enwiki.txt

inflectional:
  path: /../data/eng/eng.inflectional.v1.tsv

derivational:
  path: /../data/eng/eng.derivational.v1.tsv

model:
  path: /../data/pretrained_tokenizer_128

vocab_file:
  path: /../data/pretrained_tokenizer_128/vocab.txt

vocab_size:
  30_522
max_length:
  512
epoch:
  3
batch_size:
  128

cc_news:
  path: /../data/raw/cc_news.txt
enwiki:
  path: /../data/raw/enwiki.txt
ccnews_enwiki:
  path: /../data/raw/ccnews_enwiki.txt
