train:
  path: /../data/train.json

dev:
  path: /../data/dev.json

test:
  path: /../data/test.json

data_all:
  path: /../data/data_all.json


misclassification:
  path: /../data/misclassification.json
correct_classification:
  path: /../data/correct_classification.json

epoch: 1
batch_size: 2
max_len: 512
learning_rate: 0.0001
vocab_size: 30_522
hidden_size: 768
hidden_layer: 6
attention_heads: 12
typo_size: 1