train:
  path: /../data/cc_news_sample.txt

inflectional_path:
  path: /../data/eng/eng.inflectional.v1.tsv

derivational_path:
  path: /../data/eng/eng.derivational.v1.tsv

vocab_size:
  30_522
max_length:
  512
