train:
  path: /../data/raw/shuffled_ccnews_enwiki.txt

inflectional:
  path: /../data/eng/eng.inflectional.v1.tsv

derivational:
  path: /../data/eng/eng.derivational.v1.tsv

model:
  path: /../data/pretrained_tokenizer


vocab_size:
  30_522
max_length:
  512
epoch:
  3
batch_size:
  2

cc_news:
  path: /../data/raw/ccnews_enwiki.txt
enwiki:
  path: /../data/raw/train.txt
