train:
  path: /../data/raw/shuffled_ccnews_enwiki.txt

inflectional_path:
  path: /../data/eng/eng.inflectional.v1.tsv

derivational_path:
  path: /../data/eng/eng.derivational.v1.tsv

model_path:
  path: /../data/pretrained-bert

morphemes.json_path:
  path: /../data/morphemes.json"

vocab_size:
  30_522
max_length:
  512
epoch:
  3
batch_size:
  2

cc_news:
  path: /../data/cc_news_sample.txt
enwiki:
  path: /../data/raw/train.txt
